### ISSUE TITLE
Is it only for COG?

### ISSUE THREAD

**Issue by sharkAndshark** [DHI/terracotta#335]
Hi team! Thanks for this great repo.  We are planning to utilize Terracotta for managing our extensive collection of GeoTIFF files.

Before proceeding, does Terracotta support normal GeoTIFF files, or COG files only?  Thx!

**Comment by dionhaefner** [comment]
Cloud-optimizing is not strictly a requirement, and you can serve up pretty much any GeoTIFF. However, for large rasters this will be grossly inefficient (like 100x-1000x slower). So for performance reasons, we strongly recommend cloud optimizing for any application beyond testing.

**Comment by dionhaefner** [comment]
Looks like this answers your question. Feel free to follow up if there's something else.
