### ISSUE TITLE
Configure GDAL_CACHEMAX when running optimize-rasters

### ISSUE THREAD

**Issue by tomalrussell** [DHI/terracotta#337]
I've been tweaking this line and bumping `CACHEMAX` to several GB seems to give a nice performance improvement when I have just a few large rasters to process and RAM to spare:

https://github.com/DHI/terracotta/blob/018f96341bbfcd3876f6f89a30b0fc59ec855599/terracotta/scripts/optimize_rasters.py#L35

Is there a preferred way to make this configurable? Could be a check for existing GDAL_CACHEMAX environment variable and fall back to 512MB as a safe enough default?

**Comment by dionhaefner** [comment]
@tomalrussell How's this? https://github.com/DHI/terracotta/pull/338

**Comment by tomalrussell** [comment]
Looks good to me, thanks @dionhaefner
