### ISSUE TITLE
v0.8.4 not published in pypi

### ISSUE THREAD

**Issue by atanas-balevsky** [DHI/terracotta#341]
Hi folks,
do you intend to maintain the releases in pypi. looking at https://pypi.org/project/terracotta/ the latest there is 0.8.3

thanks in advance
nas

**Comment by j08lue** [comment]
Ah, thanks for noting, @atanas-balevsky, I did not notice that the last PyPI publication run failed. https://github.com/DHI/terracotta/actions/runs/9367664905

I'll fix it shortly.

**Comment by dionhaefner** [comment]
Thanks, 0.8.5 is released as of now :)
